### ISSUE TITLE
Please switch to typescript

### ISSUE THREAD

**Issue by alimd** [nuejs/nue#10]
Very nice idea but could you please switch to typescript. (I can help)
Thank you in advance.

**Comment by tipiirai** [comment]
I'd prefer JSDoc [@type tags](https://jsdoc.app/tags-type.html) and `.d.ts` files. I think that would be a good balance for both sides of the endless "which one is better" debate. How does that sound? Glad to receive help on that front.

**Comment by tipiirai** [comment]
I'd prefer to start with just the `.d.ts` file since that would not add any extra to the main source code

**Comment by njfamirm** [comment]
> Very nice idea but could you please switch to typescript. (I can help) Thank you in advance.

I also agree!
And I am eager to help...!

but typescript is typesafe, and `.d.ts` file don't provide this feature. As far as I understand.

**Comment by yalalalala3** [comment]
> but typescript is typesafe, and `.d.ts` file don't provide this feature. As far as I understand.

while declaration files don't offer full fledged type safety like raw typescript, modern IDEs and editors are very capable. They can provide type hints based on jsdoc comments with .d.ts, which should be sufficient in most cases.

**Comment by njfamirm** [comment]
> > but typescript is typesafe, and `.d.ts` file don't provide this feature. As far as I understand.
> 
> while declaration files don't offer full fledged type safety like raw typescript, modern IDEs and editors are very capable. They can provide type hints based on jsdoc comments with .d.ts, which should be sufficient in most cases.

A large part of the work is before the run time, which causes typing errors and prevents bugs.
Can the importance of statically typed languages be ignored?

I think it is easier to switch to typescript at the beginning of the project than a novel where there are many codes

**Comment by romanwbruce** [comment]
> > > but typescript is typesafe, and `.d.ts` file don't provide this feature. As far as I understand.
> > 
> > 
> > while declaration files don't offer full fledged type safety like raw typescript, modern IDEs and editors are very capable. They can provide type hints based on jsdoc comments with .d.ts, which should be sufficient in most cases.
> 
> A large part of the work is before the run time, which causes typing errors and prevents bugs. Can the importance of statically typed languages be ignored?
> 
> I think it is easier to switch to typescript at the beginning of the project than a novel where there are many codes

This makes too much sense, and thus it will be ignored.

**Comment by tipiirai** [comment]
> This makes too much sense, and thus it will be ignored

@romanwbruce what do you mean by this?

**Comment by tipiirai** [comment]
I don't like TypeScript personally, which is stated on the website's [FAQ page](https://nuejs.org/faq/#ts). However, I'd like to find a middle ground, much the same way as Svelte attempts to do it. Starting with the `.d.ts` file, then maybe moving to JSDoc. That would make the codebase more accessible to JS developers like me.

**Comment by alimd** [comment]
@tipiirai First of all, please read my comment in a friendly tone.
As someone with more than 20 years of experience, I think that this project could have been a great success if it had benefited from sufficient experience and enterprise structures!
I was interested to see that your ideas are very close to my thinking model.
But after studying the code structure and reading your comments about typescript, I realized that this project is nothing more than a simple student project.
You seem to have a very big idea and I'm sorry to say that you started maybe 5 to 10 years too early! (in terms of technical experience)
I still hope to have the honor of being with you in the future. But for now I have to say goodbye to you and this project.
I hope this friendly opinion will cause more reflection on the way of project implementation and more research along with reading the codes of elders.
Thank you.

**Comment by tipiirai** [comment]
@AliMD I think you are stuck into implementation details instead of focusing on what makes a good frontend toolchain. Nue focuses heavily on separation of concerns, progressive enhancement, and overall minimalism. How would you change the focus to make the project more successful?

**Comment by mchao123** [comment]
> @AliMD I think you are stuck into implementation details instead of focusing on what makes a good frontend toolchain. Nue focuses heavily on separation of concerns, progressive enhancement, and overall minimalism. How would you change the focus to make the project more successful?

仍可你的观点，但是一个大型的项目需要多人协作，无法保证其他创作者的代码质量，排查问题时将是致命的，Typescript提供了类型安全，至少可以从有限的any中快速追寻到bug。这个项目的主程序可以无需Typescript，但是至少应该让开发人员方便的使用Typescript。

**Comment by alimd** [comment]
> 仍可你的观点，但是一个大型的项目需要多人协作，无法保证其他创作者的代码质量，排查问题时将是致命的，Typescript提供了类型安全，至少可以从有限的any中快速追寻到bug。这个项目的主程序可以无需Typescript，但是至少应该让开发人员方便的使用Typescript。

الان خوشت میاد من به زبان خودم برات بنویسم و مجبور بشی بری ترجمه کنی؟! گلابی

**Comment by mchao123** [comment]
> > 仍可你的观点，但是一个大型的项目需要多人协作，无法保证其他创作者的代码质量，排查问题时将是致命的，Typescript提供了类型安全，至少可以从有限的any中快速追寻到bug。这个项目的主程序可以无需Typescript，但是至少应该让开发人员方便的使用Typescript。
> 
> الان خوشت میاد من به زبان خودم برات بنویسم و مجبور بشی بری ترجمه کنی؟!گلابی

Sorry, I had the translation feature of the Edge browser open earlier, and the browser automatically translated the language I entered into the language I use. What I meant to express previously was: I acknowledge your viewpoint, but for a large-scale project, collaboration among multiple people is necessary. It's not feasible to ensure the quality of code from other contributors, and debugging issues could be fatal. TypeScript provides type safety, which allows for quickly tracing bugs from the limited 'any' types. While the main program of this project may not necessarily require TypeScript, it should at least facilitate the convenience of TypeScript usage for developers.

**Comment by njfamirm** [comment]
> > > 仍可你的观点，但是一个大型的项目需要多人协作，无法保证其他创作者的代码质量，排查问题时将是致命的，Typescript提供了类型安全，至少可以从有限的any中快速追寻到bug。这个项目的主程序可以无需Typescript，但是至少应该让开发人员方便的使用Typescript。
> > 
> > 
> > الان خوشت میاد من به زبان خودم برات بنویسم و مجبور بشی بری ترجمه کنی؟!گلابی
> 
> Sorry, I had the translation feature of the Edge browser open earlier, and the browser automatically translated the language I entered into the language I use. What I meant to express previously was: I acknowledge your viewpoint, but for a large-scale project, collaboration among multiple people is necessary. It's not feasible to ensure the quality of code from other contributors, and debugging issues could be fatal. TypeScript provides type safety, which allows for quickly tracing bugs from the limited 'any' types. While the main program of this project may not necessarily require TypeScript, it should at least facilitate the convenience of TypeScript usage for developers.

حله داداش

**Comment by goblinfactory** [comment]
Given the goals of the author to keep everything as small as possible; and given that the author is developing most of the code by himself, not using typescript makes a lot of sense. Less is more. The project isn't 100 000 lines of code; and is small enough that a single developer can pick up and understand and read through and follow the entire codebase. Show me many other javascript libraries that you can honestly do that with? Typescript is specifically designed to solve many problems caused by large teams and enterprise needs. This isn't that and doesn't have those problems imho. 

[Adding typescript to a project can add an additional level of complexity that incurs additional costs that must also be considered](https://www.phind.com/search?q=TypeScript+comes+with+a+substantial+cost%2C+and+it+wouldn%27t+be+wise+to+ignore+it.%0A%28references+please%29&ignoreSearchResults=false&allowMultiSearch=false). How many times have you worked on a typescript project and have had to convert a strong type to `any` just because the generic types themselves get in the way of the code readability? Or, you couldnt get it to compile without doing that.

```
TypeScript comes with a substantial cost, and it wouldn't be wise to ignore it.
```

**Comment by goblinfactory** [comment]
Why are people expecting open source authors to develop a framework that's supposed to solve every single development need? if you don't like it; don't use it. Like trying to use a sports convertible to carry building material; It's not designed for that. The author (imo, `and I'm not speaking on his behalf`) is OBVIOUSLY not asking, or demanding that you use this framework for everything. It's a tool, like a hammer or screwdriver. He's asking you to consider if you want to use it, and you decide where it fits best for you. **If you don't like it, you don't have to use it. Don't say it's a hobby project;  that's just rude and ignorant.** 

If you want to contribute constructively please read through the author's vision and mission statements and any constructive feedback that helps the author and volunteers stay on point, with regards to the core vision and objectives will be most welcome. 

Otherwise if you're just complaining that the author's efforts to deliver on a **_totally remarkable vision_** doesn't match up to your expectations; then feel free to fork the project and make your own version that scratches your specific itch. That's the beauty of open source projects. If you're kind about it, we'll (or he will) probably even try to help you. 

> patient: Doctor, my head hurts when i do this! (patient bangs his head on nails instead of using hammer)
> doctor: Then don't do that!

**Comment by tipiirai** [comment]
Thank you @goblinfactory! Well said. 

One point I want to make: if someone shows me a solid change in Nue's codebase that showcases a tangible benefit of TypeScript without hurting minimalism I'm all ears. Even better, if the change would make Nue codebase _even more_ minimal and clear, then I'd be ready to change my point of view.

**Comment by goblinfactory** [comment]
> I'd prefer JSDoc [@type tags](https://jsdoc.app/tags-type.html) and `.d.ts` files. I think that would be a good balance for both sides of the endless "which one is better" debate. How does that sound? Glad to receive help on that front.

Just because we're saying we don't see an immediate need for Typescript, doesn't mean we can't explore adding "typescript support" as @tipiirai has already said. But that's very different to "switch the project to typescript".

**Comment by feribg** [comment]
In the age of static analysis tools, refactoring tools and AI non type safety is a no go. Noone will write 95% of their UI in rust, maybe 5% of performance critical code, which makes the type system interoperability between the 2 even more important (generating stubs automatically etc).  Are there any plans for it, otherwise the idea is great?

**Comment by andreyluiz** [comment]
Adding my 5 cents: my first impulse when studying Nue.js was to bias towards what I use on my current stack.
- Does it support TypeScript?
- Can I use Tailwind with it?

But as deep I went into understanding why things are designed the way they are, specially after Nuekit, I understand that we became biased by an industry of Big Techs that by pure influence drive us towards complex and uncessary code bases.

Nue.js is a testament of someone who had enough of this. And who is in the same mood, and want to start studying something that feel, looks and runs properly, will understand that things have a place and a meaning.

TypeScript and Tailwind would hurt simplicity and standards.
