### ISSUE TITLE
Is there any tutorial for beginners?

### ISSUE THREAD

**Issue by lpwm** [nuejs/nue#102]
I have to say nuejs is exactly what I expected, it seems awesome! Since React/Vue is nightmare for beginners, nuejs seems more friendly to those who stay on old school frontend technical stacks (like me🤣). I've read all the docs and blogs on the official site, but still not sure how to start a project with it. Also googled for a while but no luck. Is there any tutorial from zero? Such as a simple to-do demo?

Thanks!

**Comment by tipiirai** [comment]
Thank you for the motivation! Always good to hear that this is going to be useful for some people. At least for us oldies 😆.

But yeah.. there is no such tutorial, because Nue is not very usable at this point. Only Nue **JS** part is ready: that is templating / server-side components / and reactive  components. My goal is to release the first actually usable piece this month, which will be a static website generator with all the hot-reloading stuff in place.

**Comment by lpwm** [comment]
Wow! This month! Can't wait to see it! 😍😍😍

**Comment by tipiirai** [comment]
Nice. The minimum viable version is definitely out this month with limited documentation initially but enough to get a grasp of what's ultimately coming.
