### ISSUE TITLE
你们前端一天吃饱了没事做？有这精力来卷后端都技术总监CTO了。

### ISSUE THREAD

**Issue by 0xA1b** [nuejs/nue#104]

**Comment by deepbreath** [comment]
有一种 jsp 的视角，求求你们去改改 jsp 吧

**Comment by JackShijt** [comment]
后端一个springboot打天下，前端天天这逼那个的

**Comment by censujiang** [comment]
原神怎么你了

**Comment by LiangNiang** [comment]
agree

**Comment by lpwm** [comment]
我觉得是人家有闲有兴趣去搞这种项目, 跟咱们的卷不一样吧...

**Comment by hongkb24** [comment]
没教养

**Comment by deepbreath** [comment]
对不起，是我没教养了，实在克制不住。我的理智已经被两年前的老项目升级给消磨殆尽了。跟你们道歉，实在对不起。两年前的项目用的很多当时主流的库已经没人维护了。我不确定这个库能干到什么时候。如果没有办法坚持10年以上的长期维护。请早点告知吧，因为 start 真的是随手给的，大家说好我也觉得好。老老实实用官方的工具了， 累了。
I'm sorry, I'm uneducated, I just can't restrain myself. My sanity has been sapped by upgrading my old program two years ago. I apologize, I'm sorry. A lot of the libraries used in the project two years ago that were mainstream at the time are no longer maintained. I'm not sure how long this library will last. If there is no way to maintain it for more than 10 years. Please let us know earlier, because start is really a handful, and I feel good when people say it's good. I'm tired of using official tools.

Translated with DeepL

**Comment by tipiirai** [comment]
Hey! I'm sorry, but I cannot follow this discussion. Is there a question or issue?

**Comment by zzzzzzzzz9527** [comment]
应该和蔡徐坤有关系

**Comment by lpwm** [comment]
> Hey! I'm sorry, but I cannot follow this discussion. Is there a question or issue?

@tipiirai Nothing wrong but just some complaining/concern from Chinese frontend developer with the emerging frameworks. 
I'm very optimistic about this project, just keep going! 🍖🍖🍖

**Comment by gucovip** [comment]
造轮子很有趣。Building wheels is fun.

**Comment by ShiMeiWo** [comment]
@tipiirai It's just trolling. You may want to close the issue and report it to the GitHub management team.

**Comment by SnowGuest** [comment]
> Hey! I'm sorry, but I cannot follow this discussion. Is there a question or issue?

This is just a prankster, please ignore him and close the issue.

**Comment by SnowGuest** [comment]
This is the place to raise questions or answer difficult points about open source frameworks, not the place to complain, please close it.
I'm ashamed of you.

**Comment by xland** [comment]
楼上这位，没事的，作者如果真不喜欢这类issue，他自己会关的

**Comment by SnowGuest** [comment]
> 楼上这位，没事的，作者如果真不喜欢这类issue，他自己会关的

纯纯丢国人脸主要是

**Comment by ShiMeiWo** [comment]
> 楼上这位，没事的，作者如果真不喜欢这类issue，他自己会关的

You guys should understand that you are exposing your childish shame to the world. If you have any complaints, you shall be muttering them to the wall in your room, not here.

@tipiirai Pls close the issue ASAP.

**Comment by tipiirai** [comment]
Lol. Thanks guys!
