### ISSUE TITLE
A Couple of Questions

### ISSUE THREAD

**Issue by Darth-Ness** [nuejs/nue#114]
(Sorry if this is the wrong place for this)

1.  What is Nuemark and NueCSS?
2. Will NueJS ever run in the browser without Node/Bun?
3. How much space does NueJS  and Nuekit take up once installed?
4. Can I use NueJS and Nuekit on some pages but not others?
5. How can I help with these projects?

**Comment by tipiirai** [comment]
1a) **Nuemark** is an upcoming project that extends Markdown with sections and components. It allows you to write rich, interactive pages with purely with a Markdown-based syntax. It makes _content_ the primary thing and focus when designing pages. ie "content first". 

1b) **Nue CSS** is another upcoming project. It's essentially a CSS pre-processor, similar to SASS or Stylus, but is much more minimalistic and has smoother support to modern CSS features like variables. It also has tons of shortcuts like `mb` (margin-bottom) to make it more familiar for users of Tailwind.  However, I'm planning to integrate Lightning CSS and Stylus to Nue first. 

2) I doubt it. That would make Nue JS browser component much bigger and it would violate CSP (content security policy) due to `new Function()` or `exec`, and Nuekit makes compilation feel transparent.

3) Running `bun i nuekit` makes an empty directory weight 4.5M (next.js is ~335MB)

4) Yes. The generated output is a folder with static files. You can push that to any static serving service like S3 and Netlify.

5) In many ways. Getting to know the code, creating tests, fixing issues. Right now I need help to get `bun create nue` to work. 

Thank you!

**Comment by Darth-Ness** [comment]
Thanks for the reply.
3. Wow! That's a huge improvement! Would it be the same size for Node/NPM?
5. Okay, I'll try and see if there is any issues that I could help with.

**Comment by nobkd** [comment]
@tipiirai 
When reading about Nuemark, I thought of MDC syntax from Nuxt Content:
- [Remark implementation](https://github.com/nuxtlabs/remark-mdc) 
- [MarkdownIt implementation](https://github.com/antfu/markdown-it-mdc) 

Do you have something similar to this in mind?
 See the [spec issue](https://github.com/nuxtlabs/remark-mdc/issues/53) and [Readme](https://github.com/nuxtlabs/remark-mdc#readme)

It might be an inspiration... :shrug:

**Comment by tipiirai** [comment]
@Darth-Ness yes. The size will be the same with Node/NPM

**Comment by tipiirai** [comment]
@nobkd Nuemark syntax will be different. It aims to be good for content creators without HTML/JS skills. Think of marrying WordPress shortcodes and YAML.
