### ISSUE TITLE
error: could not determine executable to run for package create-nue

### ISSUE THREAD

**Issue by 7999999166** [nuejs/nue#163]
i installed bun , checked version --> its 1.0.23 
on running the command -- >  bun create nue@latest 
it is showing this error , please help me to ressolve 
error: could not determine executable to run for package create-nue

**Comment by Darth-Ness** [comment]
You did run `bun install nuekit --global` correct?

**Comment by nobkd** [comment]
@Darth-Ness 
You don't need to have `nuekit` installed to use `bun create nue@latest`.

@7999999166 
I can't reproduce the error, but here are some ideas / suggestions.
Can you provide system details?
Have you tried clearing the [cache](https://bun.sh/docs/install/cache)?
Have you tried using `bunx create-nue@latest` instead?

If that also does not work, have you tried using `pnpm create`, `yarn create` or `npm create` at least for generating a base project?

**Comment by 7999999166** [comment]
my system details are 
1)11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz   
2)64-bit operating system
3)Windows 11
i have allready ran this command line bun install nuekit --global before bun create nue@latest

**Comment by 7999999166** [comment]
on running command  bunx create-nue@latest
this error is comming -->

uh-oh: cast causes pointer to be null
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.23-canary.36 (86b1aa02) Windows x64
BunxCommand:
Elapsed: 8ms | User: 0ms | Sys: 0ms
RSS: 21.64MB | Peak: 21.64MB | Commit: 65.20MB | Faults: 5421
----- bun meta -----

0   00007FF64DB7FDE8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 9248 panic: cast causes pointer to be null
???:?:?: 0x7ff64ca049e1 in ??? (???)
???:?:?: 0x7ff64ca71bfe in ??? (???)
???:?:?: 0x7ff64c821492 in ??? (???)
???:?:?: 0x7ff64ead0cff in ??? (???)
???:?:?: 0x7ffb892e257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffb8a42aa57 in ??? (ntdll.dll)

**Comment by nobkd** [comment]
Oh. I wasn't expecting Windows. I thought bun didn't work properly on Windows yet, but it seems to generally run on your end?

The suggestion with `bunx` couldn't even work currently, because it isn't implemented on Windows yet. See oven-sh/bun#8045, oven-sh/bun#7942

This https://github.com/oven-sh/bun/issues/7942#issuecomment-1880173242 and this https://github.com/oven-sh/bun/issues/159#issuecomment-1204777316 say, that you can work around this with WSL for now.

Also see the general issue for Windows support: oven-sh/bun#43

So in conclusion, you could try using bun with `WSL` or use `npm`, `pnpm`, `yarn` instead for now, even if it's just for creating the project structure, and using bun to run it.

---

Not sure, if this also works on Windows:

<details>
<summary>My way of creating a `npm`-based `nue` project is currently:</summary>

- creating my project folder `my-app`
- `cd my-app`
- `npm create nue@latest`
  - name `src`
  - select my template
- `npm i -D nuekit`
  - add script `"dev": "nue -r src"`
  - add script `"build": "nue -p -r src"`

So my file tree looks something like this:
- nue
  - node_modules/
  - package.json
  - src/
    - site.yaml
    - ...
    - more template files

with a `package.json`:

```json
{
  "scripts": {
    "dev": "nue -r src",
    "build": "nue -p -r src"
  },
  "devDependencies": {
    "nuekit": "^0.2.0"
  }
}
```

</details>

Edit: also needs bun installed, because of `#!/usr/bin/env bun` in Nuekit's `cli.js`

**Comment by tipiirai** [comment]
According to Bun [installation docs](https://bun.sh/docs/installation#windows) it "provides a limited, experimental native build for Windows". I updated Nue [installation docs](https://nuejs.org/docs/) to recommend Bun only under MacOS and Linux and Node under Windows. 

Thank you @Darth-Ness and @nobkd for providing crucial help for the OP! 🙏

**Comment by paperclover** [comment]
Hi. I work on Bun. @tipiirai, can you close this issue?

It is a duplicate of https://github.com/oven-sh/bun/issues/8045

**Comment by tipiirai** [comment]
Hey, @paperdave — glad to see Bun contributors here! Bun is awesome.
