### ISSUE TITLE
feature: Any plans to add benchmark comparisons?

### ISSUE THREAD

**Issue by cbbfcd** [nuejs/nue#22]

**Comment by tipiirai** [comment]
Absolutely. I need to fix bugs, provide (many more) examples, and extend documentation first.

**Comment by cbbfcd** [comment]
@tipiirai thx your reply.

Are there any `WIP` lists out there so more people can get involved (I'd be interested of course)

**Comment by JensRoland** [comment]
I feel like the usual synthetic benchmarks are fun but generally meaningless. If I compare 100 frameworks on their ability to replace 1000 rows in a HTML table, and the difference between the best and the worst is 20 milliseconds, then saying that one is fast and the other is slow criminally disregards what JS frameworks atually do in real world applications.

Having looked at the DOM updating code in Nue JS I would speculate that Nue JS would land somewhere in the good-to-middle of the field in most of these synthetic tests (my gut feeling places it roughly around Vue or Svelte, faster than React and Angular but not as fast as Solid or Inferno), and I worry that highlighting this could lead to several unhelpful outcomes:

1. Developers might begin pointing fingers and claiming that Nue JS is 'slower' than some other framework and use this as an excuse not to try it, to discourage others from trying it, or to insist that the whole philosophy is flawed and you should just use this or that other framework "because speed", distracting from the key value proposition which IMHO has much more to do with productivity, clarity/maintainability, extensibility, reuse, real world page load performance, etc.
2. Tero might feel pressure to focus on optimizing for (gaming) these synthetic tests, rather than focusing on the cohesive high-productivity toolchain around Nue JS.
3. Worst possible outcome, Tero or other contributors trying to optimize for synthetic benchmarks might inadvertently cripple Nue JS; sacrificing DX or extensibility or other quality-of-life features on the altar of more DOM operations per millisecond

All this only to say that spending time on benchmarks might be not only premature but actually counterproductive at this stage.
