### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by caesar1shi** [nuejs/nue#248]
in render.js
```
function setAttribute(key, attribs, data) {
  let val = attribs[key]
  if (!val) return

  // TODO: check all non-strings here
  if (val.constructor === Object) return

  // attributes must be strings
  if (val === 0 || 1 * val) val = attribs[key] = '' + val
```
Condition 'val === 0' is always false at this point because the false branch of the condition '!val' at line 59 has been taken

**Comment by nobkd** [comment]
Probably explains this: https://github.com/nuejs/nue/issues/227#issuecomment-1977741020

Probably related: #193

Edit: Those are mostly unrelated. Those from my examples never reach `setAttribute`. Also, I think they have been fixed with https://github.com/nuejs/nue/commit/a3b29f5587314fb2932afb23859af837aadcb680 with `processFor` (Release happened sometime later, but I probably didn't check again.)
