### ISSUE TITLE
Pending when creating projects with bun under Windows

### ISSUE THREAD

**Issue by daliweiwei** [nuejs/nue#249]
Bun has released a Windows version
But using bun to create a nue project on Windows and execute it
Bun create nue@latest
I found that after filling in the project name, I am unable to choose the default template I want
![image](https://github.com/nuejs/nue/assets/17736196/f3f2a93f-6ce1-465e-8699-a62b71c99a3d)

**Comment by nobkd** [comment]
Will switch to windows and check this later today / tomorrow 

create-nue repo: https://github.com/nuejs/create-nue

**Comment by daliweiwei** [comment]
Thank you very much

**Comment by nobkd** [comment]
It seems like a bun for windows problem, because when using node it works. On Linux, both work just fine for me.

Windows:
It does not work, when you have bun installed, and use `npm create nue@latest`, because of the [env statement](https://github.com/nuejs/create-nue/blob/e20fb2433ec8e08cae3ad43c6a3d06e065eb4e31/cli.js#L1) at the beginning of the `cli.js`. But when you run `node <path to cli.js>`, it works fine.

So the general problem seems to lie with bun on Windows...

I will look into it further.

Edit:

Those issues might be related, even though they were for Unix systems:

- oven-sh/bun#4835
- oven-sh/bun#6052
- oven-sh/bun#7033

Will check this over the weekend / when I find the time.

**Comment by daliweiwei** [comment]
Thank you for your reply. I will continue to monitor this issue

**Comment by nobkd** [comment]
@daliweiwei can you check, if you can select different template projects with [Bun v1.1.5](https://bun.sh/blog/bun-v1.1.5)? I have checked it on my windows vm's and this issue, as well as other visual issues, seem to be fixed by the latest update.

Currently, you will still encounter a path error on copying the template files, that should get fixed by https://github.com/nuejs/create-nue/commit/86034d2176c90757fcf5affbcfee3073d8a911e9

(There still seems to be a different issue, currently, that `nue`(kit) won't build the files/run the dev server on Windows...)

**Comment by daliweiwei** [comment]
@nobkd    Yes, I upgraded bun to 1.1.5 and fixed template errors according to the instructions.
I also encountered the same problem, nue (kit) does not build files/run development servers on Windows

![image](https://github.com/nuejs/nue/assets/17736196/1a78ed00-1af3-48b5-8840-e213c34bea2a)

**Comment by daliweiwei** [comment]
Of course, this also takes us one step closer to success

**Comment by nobkd** [comment]
Good to hear that this works now.

The issue, that nuekit does not build the files on windows is also already resolved with #239 but not released yet. (also see #253)

**Comment by nobkd** [comment]
Closing this, as this issue seems to be resolved.
Feel free to reopen or comment on this, if you have further problems or encounter this issue (again).

**Comment by daliweiwei** [comment]
I modified my local nuekit based on the reference and it was indeed successfully launched.
But I also discovered a new problem. I created a project based on simple crm, and after I successfully started running, I found that the files in the corresponding img directory did not seem to be packaged and output to the corresponding packaging directory/ Under dist/dev

![image](https://github.com/nuejs/nue/assets/17736196/18c806b4-a18e-4849-94c8-516202f88e9e)
![image](https://github.com/nuejs/nue/assets/17736196/2f2cea34-d57d-488d-ab3b-b0611bcdc87d)

**Comment by nobkd** [comment]
Have you already tried deleting the `.dist` directory and re-running nue?

**Comment by daliweiwei** [comment]
I deleted the. dist directory and rerun nue, and found that this issue has been resolved. Thank you

**Comment by vai** [comment]
Can't run the project using default instructions from the docs yet.

**Comment by nobkd** [comment]
@vai 
If you are on Windows, you're probably experiencing issues with `create-nue` (check the code section of this pr: nuejs/create-nue#43) or with the `nue` command from `nuekit`-package which has been fixed (check the code section: #239) but no release has happened after the merge. :(

If you want to, you can do those fixes yourself, e.g. by installing `create-nue` globally and replacing the lines by hand. The same goes for `nuekit`, though I personally would install it locally in your project and then cahnge it in the `node_modules`, because you will see the installed packages and probably not try to update `nue` instead of `nuekit` later on.

Good luck.
If you still experience issues, feel free to ping me or open a new issue / discussion

**Comment by vai** [comment]
No worries. It worked from within WSL (although not on `/mnt/c/`, use a wsl based path), just also meant a note to others that bump into it, that it's still open till your merge of #239 / related.
